version: '3'
services:
  selenium-server:
    image: selenium/standalone-firefox:4.16.1-20231219
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: 2g
    network_mode: host

  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - selenium-server
    network_mode: host

